# Generated by Django 2.2.1 on 2019-05-23 19:12

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('paulaapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prospect',
            options={'ordering': ['last_name', 'first_name', 'prospect_email', 'prospect_phone']},
        ),
        migrations.AlterField(
            model_name='prospect',
            name='prospect_phone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None),
        ),
    ]
