# Generated by Django 2.2.1 on 2019-05-23 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paulaapp', '0002_auto_20190523_1912'),
    ]

    operations = [
        migrations.AddField(
            model_name='prospect',
            name='buy_new_const_only',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='prospect',
            name='own_UP',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='prospect',
            name='own_property',
            field=models.BooleanField(default=False),
        ),
    ]
