# Generated by Django 2.2.1 on 2019-05-23 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paulaapp', '0004_auto_20190523_2008'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prospect',
            old_name='buy_new_const_only',
            new_name='buy_new_construction_only',
        ),
        migrations.RenameField(
            model_name='prospect',
            old_name='own_UP',
            new_name='owns_UP',
        ),
        migrations.RenameField(
            model_name='prospect',
            old_name='own_property',
            new_name='owns_property',
        ),
    ]
