# Generated by Django 2.2.1 on 2019-05-29 05:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('paulaapp', '0006_document'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prospect',
            name='owns_UP',
        ),
        migrations.RemoveField(
            model_name='prospect',
            name='owns_property',
        ),
        migrations.AddField(
            model_name='prospect',
            name='date_added',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prospect',
            name='day_of_week',
            field=models.CharField(choices=[('SAT', 'Saturday'), ('SUN', 'Sunday')], default=django.utils.timezone.now, max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prospect',
            name='first_visit',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prospect',
            name='multiple_visits',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='prospect',
            name='notes',
            field=models.TextField(default='', max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prospect',
            name='priority',
            field=models.CharField(choices=[('HI', 'High'), ('LO', 'Low'), ('MA', 'Maybe'), ('PU', 'Purchased')], default='MA', max_length=2),
        ),
        migrations.AddField(
            model_name='prospect',
            name='referral_source',
            field=models.CharField(default='U', max_length=50),
        ),
        migrations.AddField(
            model_name='prospect',
            name='rent_or_own',
            field=models.CharField(choices=[('R', 'Renting'), ('O', 'Own property'), ('U', 'Unknown')], default='U', max_length=1),
        ),
        migrations.AlterField(
            model_name='prospect',
            name='prospect_phone',
            field=models.CharField(default=None, max_length=12),
        ),
    ]
