# Generated by Django 2.2.1 on 2019-05-29 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paulaapp', '0009_auto_20190529_0537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prospect',
            name='priority',
            field=models.CharField(choices=[('HI', 'High'), ('LO', 'Low'), ('MI', 'Middle'), ('PU', 'Purchased')], max_length=2),
        ),
    ]
