# Generated by Django 2.2.1 on 2019-05-29 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paulaapp', '0010_auto_20190529_0539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prospect',
            name='rent_or_own',
            field=models.CharField(choices=[('R', 'Renting'), ('O', 'Own property'), ('U', 'Unknown')], max_length=1),
        ),
    ]
