# Generated by Django 2.2.1 on 2019-06-01 19:45

from django.db import migrations, models
import uuid_upload_path.storage


class Migration(migrations.Migration):

    dependencies = [
        ('paulaapp', '0011_auto_20190529_0540'),
    ]

    operations = [
        migrations.AddField(
            model_name='prospect',
            name='prospect_card',
            field=models.FileField(blank=True, null=True, upload_to=uuid_upload_path.storage.upload_to),
        ),
        migrations.AlterField(
            model_name='prospect',
            name='notes',
            field=models.TextField(blank=True, max_length=1000),
        ),
    ]
