# Generated by Django 2.2.1 on 2019-06-01 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paulaapp', '0012_auto_20190601_1945'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prospect',
            old_name='day_of_week',
            new_name='first_visit_day_of_week',
        ),
        migrations.AddField(
            model_name='prospect',
            name='date_most_recent_visit',
            field=models.DateField(null=True),
        ),
    ]
