# Generated by Django 2.2.1 on 2019-06-01 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paulaapp', '0013_auto_20190601_2003'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prospect',
            options={'ordering': ['first_visit']},
        ),
        migrations.RemoveField(
            model_name='prospect',
            name='date_most_recent_visit',
        ),
    ]
