# Generated by Django 2.2.1 on 2019-06-01 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paulaapp', '0015_prospect_date_most_recent_visit'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prospect',
            options={'ordering': ['last_name', 'first_name', 'prospect_email', 'prospect_phone']},
        ),
        migrations.RemoveField(
            model_name='prospect',
            name='date_most_recent_visit',
        ),
    ]
