# Generated by Django 2.2.1 on 2019-06-01 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paulaapp', '0016_auto_20190601_2013'),
    ]

    operations = [
        migrations.AddField(
            model_name='prospect',
            name='date_most_recent_visit',
            field=models.DateField(null=True),
        ),
    ]
