# Generated by Django 2.2.1 on 2019-06-02 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paulaapp', '0017_prospect_date_most_recent_visit'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prospect',
            options={'ordering': ['-date_most_recent_visit']},
        ),
        migrations.AddField(
            model_name='prospect',
            name='priority_color',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
