# Generated by Django 2.2.1 on 2019-06-06 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paulaapp', '0019_remove_prospect_priority_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='prospect',
            name='action_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='prospect',
            name='action_item',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
