# Generated by Django 2.2.1 on 2019-06-09 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paulaapp', '0020_auto_20190606_0617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prospect',
            name='action_item',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='Document',
        ),
    ]
