# Generated by Django 2.2.3 on 2019-08-04 00:45

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('paulaapp', '0021_auto_20190609_2242'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('visit_date', models.DateField()),
                ('visit_notes', models.CharField(max_length=100)),
                ('prospect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paulaapp.Prospect')),
            ],
            options={
                'ordering': ['-visit_date'],
            },
        ),
    ]
