# Generated by Django 2.2.3 on 2019-08-09 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paulaapp', '0022_visit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prospect',
            name='action_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
