# Generated by Django 2.2.3 on 2019-08-20 00:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('paulaapp', '0023_auto_20190809_1912'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prospect',
            name='first_visit',
        ),
        migrations.AlterField(
            model_name='visit',
            name='prospect',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='paulaapp.Prospect'),
        ),
    ]
